"""Test

Revision ID: 3ec73b3f1df8
Revises: 
Create Date: 2025-03-09 12:16:23.141525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec73b3f1df8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('test')

    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=True),
    sa.Column('archived', sa.BOOLEAN(), nullable=True),
    sa.Column('onhold', sa.BOOLEAN(), nullable=True),
    sa.Column('prio', sa.INTEGER(), nullable=True),
    sa.Column('list_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
