"""Remove Test

Revision ID: 922b6fdb5576
Revises: 3ec73b3f1df8
Create Date: 2025-03-09 12:20:58.908162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922b6fdb5576'
down_revision = '3ec73b3f1df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('test')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
